env:
    browser: true
    es2021: true
    webextensions: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - eslint-config-prettier
    - plugin:prettier/recommended
    - plugin:import/recommended
    - airbnb-base
    - prettier

overrides: [files: ['**/*.ts', '**/*.tsx']]
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
    project: './tsconfig.json'
plugins:
    - '@typescript-eslint'
    - prettier
settings:
    react:
        version: 'detect'
rules: { 'comma-dangle': 0, import/no-unresolved: 0, import/extensions: 0 }
